name: lend_loop
description: A local-first mobile app for private lending and borrowing records.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.13.1 <4.0.0'
  flutter: 3.47.1

dependencies:
  crypto: 3.0.7
  drift: 2.34.3
  flutter:
    sdk: flutter
  flutter_local_notifications: 19.4.2
  image_picker: 1.2.3
  path_provider: 2.1.6
  sqlite3: 3.5.2
  timezone: 0.10.1

dev_dependencies:
  build_runner: 2.16.0
  drift_dev: 2.34.5
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
